"""Initial schema: sessions, attempts, scores

Revision ID: 22c4d80f2edf
Revises: 
Create Date: 2025-11-11 13:24:29.815567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c4d80f2edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_trivia_sessions_session_id'), 'trivia_sessions', ['session_id'], unique=False)
    op.create_table('user_scores',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('cumulative_score', sa.Integer(), nullable=False),
    sa.Column('first_correct_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_scores_user_id'), 'user_scores', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_scores_username'), 'user_scores', ['username'], unique=True)
    op.create_table('attempt_records',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('submitted_answer', sa.String(length=200), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['trivia_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_attempt_records_attempt_id'), 'attempt_records', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_records_session_id'), 'attempt_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attempt_records_submitted_at'), 'attempt_records', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_attempt_records_username'), 'attempt_records', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_records_username'), table_name='attempt_records')
    op.drop_index(op.f('ix_attempt_records_submitted_at'), table_name='attempt_records')
    op.drop_index(op.f('ix_attempt_records_session_id'), table_name='attempt_records')
    op.drop_index(op.f('ix_attempt_records_attempt_id'), table_name='attempt_records')
    op.drop_table('attempt_records')
    op.drop_index(op.f('ix_user_scores_username'), table_name='user_scores')
    op.drop_index(op.f('ix_user_scores_user_id'), table_name='user_scores')
    op.drop_table('user_scores')
    op.drop_index(op.f('ix_trivia_sessions_session_id'), table_name='trivia_sessions')
    op.drop_table('trivia_sessions')
    # ### end Alembic commands ###
